name: reading_app
description: Reading app. App for learn document and collaborations
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # The following adds the GoogleNav for BottomBar
  google_nav_bar: ^5.0.6

  # The following adds services Firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.4.4
  firebase_storage: ^10.3.8

  # The following adds Speed dial for warning messages
  flutter_speed_dial: ^6.0.0

  # The following adds the picker for acces image on device
  image_picker: ^0.8.5+3
 
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

